language: node_js
node_js:
    - "node"
    - "lts/*"
    - "8"
    - "7"
    - "6"
os:
    - linux
    - osx
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential libudev-dev; fi
script:
    - npm test
    - npm run prepublishOnly
    - npm run docs
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./api-reference
    on:
        tags: true
